color: 
        0:  [[85, 255, 230], [50, 45, 35]]
        1:  [[140, 255, 255], [100, 100, 100]]
        2:  [[15, 255, 255], [0, 100, 100], [180, 255, 255], [160, 100, 100]]

shape:
        0:
                num_color:  0
                mode:  "START"
                type_shape:  "rectangle"
                shape:  [[100, 100], [50, 50]]
        1:
                num_color:  1
                mode:  "END"
                type_shape:  "rectangle"
                shape:  [[550, 100], [50, 50]]
        2:
                num_color:  0
                mode:  "RECOGNITION"
                type_shape:  "ellipse"
                shape:  [[550, 300], [100, 50]]
        3:
                num_color:  2
                mode:  "ERROR"
                type_shape:  "ellipse"
                shape:  [[0, 300], [100, 50]]

define:
        camera_num:  0
        min_area:  500
        what_record:  "both"
        record_time:  600
        acolor_detection:
                shape:  [[400,200],[40,40]]
                num_attempt: 10
        recommend_video:  True
        recommend_processed:  True
        num_recommend_slow:  0
        num_recommend_fast:  0

debug:
        permit_show_contours:  True
